version: '3'
services:
  scanner:
    build:
      context: ./scanner
    ports:
      - "3000:3000"
    environment:
      - HISTORY_URL=http://history:4000/history
    depends_on:
      - history

  history:
    build:
      context: ./history
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
